### PR TITLE
 Adapt scripts to find the current directory and use it in systemd st…

### LINKED ISSUE #1: Adapt scripts to find the current directory and use it in systemd startup file
After a few tries, here is a way to find the directory where the script is in bash:
```bash
source_dir=$( cd "$(dirname "$0")" ; pwd )
```
This is more complex than dirname $0 but gives you the full normalized directory.

Then we can use it to replace the name in the startup file.

### PR DESCRIPTION
**Pull request by julienw**
…artup file (Closes #1)

### CODE REVIEW

**Comment by julienw** [comment]
(still testing)

**Comment by julienw** [comment]
OK I think it works for me :) @russnicoletti what do you think ?

**Comment by russnicoletti** [comment]
As we discussed in the standup today, let's remove the 'sudo' in the script and continue to document in the README that the script should be run as root. Btw, I edited the script to remove 'sudo' everywhere and it works fine when the script itself is executed as root. Can you update your patch to remove the 'sudo's and then merge it?

**Comment by russnicoletti** [comment]
I've merged the patch as-as (with 'sudo' in the script) because I realized by latest commit has broken the functionality. We can remove the 'sudo' from the script later.

**Pull request merged**
